<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param int $post
     * @return \Doctrine\ORM\Query
     */
    public function getAllCommentsByPost($post)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Comment c WHERE c.post = :id');
        $query->setParameters(array('id' => $post));
        return $query->getResult();
    }


}
