<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    public function getAllPosts()
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:Post c ORDER BY c.id DESC');
        return $query;
    }

    public function getPostsByCategory($id, $currentPage = 1)
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:Post c WHERE c.category = :id');
        $query->setParameters(array('id' => $id));
        return $query->getResult();
    }

    public function getPostsByAuthor($id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:Post c WHERE c.author = :id');
        $query->setParameters(array('id' => $id));
        return $query->getResult();

    }

    public function searchPostByTitle($criteria)
    {
         $query = $this->createQueryBuilder('post')
            ->andWhere('post.title LIKE :criteria')
            ->setParameter(':criteria', '%'.$criteria.'%')
            ->getQuery()
            ->getResult();
        return $query;
    }

    public function paginate($dql, $page = 1, $limit = 5)
    {
        $pagination = new Paginator($dql);
        $pagination->getQuery()
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);
        return $pagination;
    }
}
