<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserByAuthor($id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:User c WHERE c.author = :id');
        $query->setParameters(array('id' => $id));
        return $query->getResult();
    }
}
